//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indieeye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int Id { get; set; }
        public string IdentificationNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Monument { get; set; }
        public string DateOfVisit { get; set; }
        public bool IsUid { get; set; }
    }
}
